server:
  port: 9090

spring:
  profiles:
    active: dev
  main:
    # 解决Bean重复定义问题
    allow-bean-definition-overriding: true
    # date统一返回时间戳
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true

mybatis-plus:
  mapper-locations: classpath*:/mapping/*.xml
  typeAliasesPackage: com.cf.sqlTest.dao.po
  config-location: classpath:/mybatis-config.xml
  global-config:
    sql-parser-cache: true
    refresh: true


logging:
  level:
    org.redisson.connection.DNSMonitor: error
    org.apache.http.wire: error

# 切面表达式expression
pointCut: public .* com.cf.sqlTest.service..*Service..*(.*)
# 切面类
aspectClass: com.cf.sqlTest.aspect.LogAspect
# 前置通知回调方法
aspectBefore: before
# 后置通知回调方法
aspectAfter: after
# 异常通知回调方法
aspectAfterThrow: afterThrowing
# 异常类型捕捉
aspectAfterThrowingName: java.lang.Exception